### ISSUE TITLE
サービスの目的が視覚的によくわからない

### ISSUE THREAD

**Issue by JunichiIto** [koheitakahashi/sound_links#107]
何をするサービスか、どういうときに使うサービスか、よくわからなかった。
楽曲を検索して終わり？って思ってしまった。
よくみると、トップに「検索した楽曲のリンクを、ワンクリックでまとめてコピーすることができます」って書いてあったり、「この曲をシェアする」リンクがあったりするけど、視覚的な主張が弱くてまったく視界に入ってこなかった。
僕みたいな悪いユーザーは説明を読まずに、とりあえず動かして何ができるか確認する、という行動を取るので、説明を読まなくても「何をするサービスか、どういうときに使うサービス」か一目でわかるようなデザインになってるとうれしい。（めちゃくちゃ難しいのはわかるけど！！）

**Comment by koheitakahashi** [comment]
issue の起票ありがとうございました 🙌 
#121 の PR で以下のように図を交えてサービスの目的を強調するようにしてみました。

0.1.1 のバージョンよりは、サービスの目的を伝えることができたと思われるので、この issue はクローズさせていただきます 🙏 

| トップページ|
| :---: |
| <img src=https://user-images.githubusercontent.com/51867807/135699976-fc4c7cc1-ce11-4986-9f45-f254c6656e3b.png  width=80%> |
