### ISSUE TITLE
対応サービスが少ない

### ISSUE THREAD

**Issue by JunichiIto** [koheitakahashi/sound_links#108]
AmazonやYouTube Musicにも対応してほしい。（APIがないのかな？）
対応予定はあるのか、技術的に無理なのか、どこかに記述があるといいかも。

**Comment by koheitakahashi** [comment]
issue の起票ありがとうございました 🙌 

現状APIが公開されている音楽配信サービスが調べる限り AppleMusic・Spotify・KKBOX・YouTube（音楽配信サービスではないですが）でした。

YouTubeはAPIが公開されていますが、レコーディングに対して付与されるISRCという国際的なレコーディング識別子の提供がなかったため、他のAPIから取得した楽曲情報と一致する楽曲なのかの判断ができず断念したという経緯があります。（他のAPIは ISRC が提供されており、コード内では同じ ISRC かどうかで同一の楽曲かどうかの判断をしています）

対応サービスの補足の文言を #121 の PR で追加しました。（赤枠部分）
対応サービスの拡大は目指していきたいところですが、補足の文章を追加したことでこの issue の主題をある程度達成できたと思われるのでクローズさせていただきます 🙏 

| トップページ|
| :---: |
| ![Screen Shot 2021-10-02 at 10 42 44 copy](https://user-images.githubusercontent.com/51867807/135700096-736bb412-336d-43ef-997d-7daa73e03aec.png) |
