### ISSUE TITLE
ページングの表示がわかりづらい

### ISSUE THREAD

**Issue by JunichiIto** [koheitakahashi/sound_links#109]
「< 1ページ目 >」という表示だと、1ページ分しかデータないものだと勘違いしてしまった。「>」をクリックして2ページ目があることに初めて気づいた。

**Comment by koheitakahashi** [comment]
issue の起票ありがとうございました 🙌 
ページネーションのデザインですが、以下のように少し変更してみました。（スクショの赤枠部分）

若干まだわかりづらさがあるかもしれませんが、0.1.1 バージョンよりは分かりやすくなったと考えています。
そのため、この issue の目的はある程度達成できたと思われるのでクローズさせていただきます 🙏 

| 検索結果ページのページネーション|
| :---: |
| <img src=https://user-images.githubusercontent.com/51867807/135700595-48d27b4c-edc4-49d7-b025-821f1f43b6e1.png  width=80%> |
