### ISSUE TITLE
アイコンの並びに一貫性がない

### ISSUE THREAD

**Issue by JunichiIto** [koheitakahashi/sound_links#110]
トップページでは「Apple, Spotify KKBOX」の順でアイコンが並んでいるが、検索結果一覧では「Spotify, Apple, KKBOX」の順なので一貫性がない。

**Comment by koheitakahashi** [comment]
issue の起票ありがとうございました 🙌 
こちら、 #121 の PR で対応しました。

この issue の目的は達成できたと思われるのでクローズさせていただきます 🙏 

|トップページ|検索結果ページ|
|:---: |:----:|
| <img src=https://user-images.githubusercontent.com/51867807/135700423-e845293e-056d-4996-b534-e066f41a4e18.png  width=80%> | <img src=https://user-images.githubusercontent.com/51867807/135700430-c6430a73-e2f7-43c6-8ba0-354d2c799f50.png  width=80%> |
