### ISSUE TITLE
生成されたURLに https://sound-links.com/ のリンクを含める

### ISSUE THREAD

**Issue by JunichiIto** [koheitakahashi/sound_links#139]
## 概要

生成されたURLに https://sound-links.com/ のリンクを含める

例

```
108(AKAIKO-EN)
Spotify
https://open.spotify.com/track/1YE6fwxFjJqO64u7QTmt9Y
Apple Music
https://music.apple.com/jp/album/108/1442591460?i=1442591823
KKBOX
https://www.kkbox.com/jp/ja/song/GcVzY14IG9o2dhsY2dhsY0PL-index.html

Created by https://sound-links.com/
```

## 誰が使うか

SoundLinksで楽曲をシェアしたい人

## 何のために

「このURL一覧はSoundLinksというサービスで作ったんだよ、みんな使ってみてね！」ということもシェアするために

**Comment by koheitakahashi** [comment]
isse の起票ありがとうございます〜 🙌 
たしかに、サービスを知ってもらうためにもリンクを含めた方が良さそうに思いました 😄 

https://github.com/koheitakahashi/sound_links/pull/140 の PR で対応し、本番環境にデプロイしましたのでクローズします〜

**Comment by JunichiIto** [comment]
対応されていることを確認しました。どうもありがとうございます！
